<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 13px; color: #333; margin: 0; padding: 0; }
        .page { padding: 40px; }
        .header { display: flex; justify-content: space-between; margin-bottom: 40px; border-bottom: 2px solid #4f46e5; padding-bottom: 20px; }
        .brand { font-size: 24px; font-weight: bold; color: #4f46e5; }
        .brand-sub { font-size: 12px; color: #888; margin-top: 4px; }
        .invoice-title { text-align: right; }
        .invoice-title h1 { font-size: 32px; color: #4f46e5; margin: 0; }
        .invoice-title .invoice-number { font-size: 14px; color: #888; }
        .meta { display: flex; justify-content: space-between; margin-bottom: 30px; }
        .meta-block h4 { margin: 0 0 6px; font-size: 11px; text-transform: uppercase; color: #888; letter-spacing: 1px; }
        .meta-block p { margin: 0; font-size: 14px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
        thead tr { background-color: #4f46e5; color: white; }
        thead th { padding: 10px 14px; text-align: left; font-size: 12px; text-transform: uppercase; }
        tbody tr:nth-child(even) { background-color: #f5f5f5; }
        tbody td { padding: 12px 14px; border-bottom: 1px solid #e5e5e5; }
        .totals { width: 260px; margin-left: auto; }
        .totals table { margin-bottom: 0; }
        .totals td { padding: 8px 10px; }
        .totals .total-row { font-weight: bold; font-size: 15px; background-color: #4f46e5; color: white; }
        .status-badge { display: inline-block; padding: 3px 10px; border-radius: 12px; font-size: 11px; font-weight: bold; text-transform: uppercase; }
        .status-paid { background-color: #d1fae5; color: #065f46; }
        .status-pending { background-color: #fef3c7; color: #92400e; }
        .status-overdue { background-color: #fee2e2; color: #991b1b; }
        .footer { text-align: center; font-size: 11px; color: #aaa; border-top: 1px solid #eee; padding-top: 16px; margin-top: 20px; }
    </style>
</head>
<body>
<div class="page">

    <div class="header">
        <div>
            <div class="brand">MyCRM</div>
            <div class="brand-sub">crm.juliowebmaster.com</div>
        </div>
        <div class="invoice-title">
            <h1>INVOICE</h1>
            <div class="invoice-number">#{{ str_pad($invoice->id, 5, '0', STR_PAD_LEFT) }}</div>
        </div>
    </div>

    <div class="meta">
        <div class="meta-block">
            <h4>Billed To</h4>
            <p><strong>{{ $invoice->client->name }}</strong></p>
            @if($invoice->client->company)
                <p>{{ $invoice->client->company }}</p>
            @endif
            <p>{{ $invoice->client->email }}</p>
            @if($invoice->client->phone_number)
                <p>{{ $invoice->client->phone_number }}</p>
            @endif
        </div>
        <div class="meta-block" style="text-align: right;">
            <h4>Invoice Details</h4>
            <p><strong>Issue Date:</strong> {{ \Carbon\Carbon::parse($invoice->created_at)->format('M d, Y') }}</p>
            <p><strong>Due Date:</strong> {{ \Carbon\Carbon::parse($invoice->due_date)->format('M d, Y') }}</p>
            <p>
                <strong>Status:</strong>
                <span class="status-badge status-{{ $invoice->status }}">{{ ucfirst($invoice->status) }}</span>
            </p>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Description</th>
                <th style="text-align: right;">Amount</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Services rendered for {{ $invoice->client->company ?? $invoice->client->name }}</td>
                <td style="text-align: right;">${{ number_format($invoice->amount, 2) }}</td>
            </tr>
        </tbody>
    </table>

    <div class="totals">
        <table>
            <tr>
                <td>Subtotal</td>
                <td style="text-align: right;">${{ number_format($invoice->amount, 2) }}</td>
            </tr>
            <tr class="total-row">
                <td>Total</td>
                <td style="text-align: right;">${{ number_format($invoice->amount, 2) }}</td>
            </tr>
        </table>
    </div>

    <div class="footer">
        Thank you for your business! &mdash; Generated by MyCRM on {{ now()->format('M d, Y') }}
    </div>

</div>
</body>
</html>
